const menu = [
  {
    name: "artesanal",
    description: "",
    image: "",
    price: "1500",
    category: "cervezas",
  },
  {
    name: "heinkeken lata",
    description: "",
    image: "",
    price: "1600",
    category: "cervezas",
  },
  {
    name: "heinken botella 330cc",
    description: "",
    image: "",
    price: "1400",
    category: "cervezas",
  },
  {
    name: "corona botella 330cc",
    description: "",
    image: "",
    price: "1600",
    category: "cervezas",
  },
  {
    name: "corona lata 269cc",
    description: "",
    image: "",
    price: "1300",
    category: "cervezas",
  },
  {
    name: "blue moon",
    description: "",
    image: "",
    price: "2000",
    category: "cervezas",
  },
  {
    name: "agua",
    description: "",
    image: "",
    price: "700",
    category: "sin alcohol",
  },
  {
    name: "gaseosas",
    description: "",
    image: "",
    price: "700",
    category: "sin alcohol",
  },
  {
    name: "red bull",
    description: "",
    image: "",
    price: "1500",
    category: "sin alcohol",
  },
  {
    name: "fernet",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "cinzano",
    description: "",
    image: "",
    price: "1800",
    category: "tragos",
  },
  {
    name: "gin tonic harrisons",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "campari tonic",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "aperol + cinzano to spritz",
    description: "",
    image: "",
    price: "2200",
    category: "tragos",
  },
  {
    name: "cynar julep",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "whisky chivas",
    description: "",
    image: "",
    price: "3500",
    category: "tragos",
  },
  {
    name: "shot de jagermeister",
    description: "",
    image: "",
    price: "2200",
    category: "tragos",
  },
  {
    name: "jager con red-bull",
    description: "",
    image: "",
    price: "3000",
    category: "tragos",
  },
  {
    name: "cuba libre",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "vodka y naranja",
    description: "",
    image: "",
    price: "2000",
    category: "tragos",
  },
  {
    name: "vodka y red bull",
    description: "",
    image: "",
    price: "2800",
    category: "tragos",
  },
  {
    name: "malbec km 210",
    description: "",
    image: "",
    price: "",
    category: "vinos y espumantes",
    serving: [
      {
        description: "copa",
        price: "1500",
      },
      {
        description: "botella",
        price: "5500",
      },
    ],
  },
  {
    name: "bonarda km 210",
    description: "",
    image: "",
    price: "",
    category: "vinos y espumantes",
    serving: [
      {
        description: "copa",
        price: "1500",
      },
      {
        description: "botella",
        price: "5500",
      },
    ],
  },
  {
    name: "ferox reserva malbec",
    description: "",
    image: "",
    price: "",
    category: "vinos y espumantes",
    serving: [
      {
        description: "copa",
        price: "1700",
      },
      {
        description: "botella",
        price: "6000",
      },
    ],
  },
  {
    name: "vino blanco (consultar variedades)",
    description: "",
    image: "",
    price: "",
    category: "vinos y espumantes",
  },
  {
    name: "gouggenheim brut",
    description: "",
    image: "",
    price: "5000",
    category: "vinos y espumantes",
  },
  {
    name: "maria codorniu extra brut",
    description: "",
    image: "",
    price: "4500",
    category: "vinos y espumantes",
  },
  {
    name: "pizza muzzarella",
    description: "",
    image: "",
    price: "3000",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "media pizza muzzarella",
    description: "",
    image: "",
    price: "2000",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "pizza napolitana",
    description: "",
    image: "",
    price: "3300",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "media pizza napolitana2200",
    description: "",
    image: "",
    price: "",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "empanada de carne",
    description: "",
    image: "",
    price: "700",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "empanada jamon y queso",
    description: "",
    image: "",
    price: "700",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "empanada leña (6 quesos)",
    description: "",
    image: "",
    price: "700",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "empanada pollo",
    description: "",
    image: "",
    price: "700",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "empanada humita",
    description: "",
    image: "",
    price: "700",
    category: "pizzas y empanadas by leña",
  },
  {
    name: "nuggets de pollo",
    description: "",
    image: "",
    price: "1800",
    category: "para picar",
  },
  {
    name: "milanesa en tiritas",
    description: "",
    image: "",
    price: "2200",
    category: "para picar",
  },
  {
    name: "porcion de papas",
    description: "",
    image: "",
    price: "1600",
    category: "para picar",
  },
  {
    name: "mix de nuggets, milanesa y papas",
    description: "",
    image: "",
    price: "3500",
    category: "para picar",
  },
  {
    name: "hummus de zanahoria",
    description: "",
    image: "",
    price: "1800",
    category: "para picar",
  },
  {
    name: "mila con fritas",
    description: "",
    image: "",
    price: "2900",
    category: "platos",
  },
  {
    name: "milanesa napo con fritas",
    description: "",
    image: "",
    price: "3200",
    category: "platos",
  },
];
